class AppStrings {
  static Map<String, Map<String, String>> localizedValues = {
    'vi': {
      'home': 'Trang chủ',
      'favorite': 'Yêu thích',
      'settings': 'Cài đặt',
      'trending': 'Phim Hot',
      'search_hint': 'Tìm kiếm phim...',
      'no_movies': 'Không tìm thấy phim nào!',
      'no_favorites': 'Chưa có phim nào trong danh sách yêu thích!',
      'dark_mode': 'Giao diện tối (Dark Mode)',
      'enabled': 'Đang bật',
      'disabled': 'Đang tắt',
      'language': 'Ngôn ngữ / Language',
      'version': 'Phiên bản ứng dụng',
      'select_language': 'Chọn ngôn ngữ',
      'overview': 'Nội dung phim',
      'release_date': 'Ngày phát hành',
      'rating': 'Đánh giá',
      'add_to_favorite': 'Thêm vào yêu thích',
      'remove_favorite': 'Đã thích',
      'similar_movies': 'Phim tương tự',
      'all': 'Tất cả',
    },
    'en': {
      'home': 'Home',
      'favorite': 'Favorites',
      'settings': 'Settings',
      'trending': 'Trending Movies',
      'search_hint': 'Search movies...',
      'no_movies': 'No movies found!',
      'no_favorites': 'No favorite movies yet!',
      'dark_mode': 'Dark Mode',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'language': 'Language',
      'version': 'App Version',
      'select_language': 'Select Language',
      'overview': 'Overview',
      'release_date': 'Release Date',
      'rating': 'Rating',
      'add_to_favorite': 'Add to Favorite',
      'remove_favorite': 'Favorited',
      'similar_movies': 'Similar Movies',
      'all': 'All',
    },
    'zh': {
      'home': '首页',
      'favorite': '收藏',
      'settings': '设置',
      'trending': '热门电影',
      'search_hint': '搜索电影...',
      'no_movies': '未找到电影！',
      'no_favorites': '收藏夹中还没有电影！',
      'dark_mode': '深色模式',
      'enabled': '已启用',
      'disabled': '已禁用',
      'language': '语言 / Language',
      'version': '应用版本',
      'select_language': '选择语言',
      'overview': '剧情简介',
      'release_date': '上映日期',
      'rating': '评分',
      'add_to_favorite': '加入收藏',
      'remove_favorite': '已收藏',
      'similar_movies': '类似电影',
      'all': '全部',
    },
    'ko': {
      'home': '홈',
      'favorite': '즐겨찾기',
      'settings': '설정',
      'trending': '인기 영화',
      'search_hint': '영화 검색...',
      'no_movies': '영화를 찾을 수 없습니다!',
      'no_favorites': '즐겨찾기에 영화가 없습니다!',
      'dark_mode': '다크 모드',
      'enabled': '켜짐',
      'disabled': '꺼짐',
      'language': '언어 / Language',
      'version': '앱 버전',
      'select_language': '언어 선택',
      'overview': '줄거리',
      'release_date': '개봉일',
      'rating': '평점',
      'add_to_favorite': '즐겨찾기 추가',
      'remove_favorite': '즐겨찾기됨',
      'similar_movies': '비슷한 영화',
      'all': '전체',
    },
    'ja': {
      'home': 'ホーム',
      'favorite': 'お気に入り',
      'settings': '設定',
      'trending': 'トレンド映画',
      'search_hint': '映画を検索...',
      'no_movies': '映画が見つかりません！',
      'no_favorites': 'お気に入りに追加された映画はありません！',
      'dark_mode': 'ダークモード',
      'enabled': '有効',
      'disabled': '無効',
      'language': '言語 / Language',
      'version': 'アプリバージョン',
      'select_language': '言語を選択',
      'overview': '概要',
      'release_date': '公開日',
      'rating': '評価',
      'add_to_favorite': 'お気に入りに追加',
      'remove_favorite': 'お気に入り済み',
      'similar_movies': '類似の映画',
      'all': 'すべて',
    },
  };

  static String get(String key, String langCode) {
    return localizedValues[langCode]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}